KNN Regression

In [1]:
#import necessary libiary to read file |
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt


In [2]:
# import dataset 
df = pd.read_csv('weight-height.csv')
df.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [3]:
df.shape

(8555, 3)

# import necessary algo for the task 

In [4]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error

# seperate the dataset

In [5]:
df.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

# encoding 

In [6]:
 laben = LabelEncoder()

In [7]:
df.Gender= laben.fit_transform(df.Gender)


In [8]:
df.head(7000)

Gender     Height      Weight
0          1  73.847017  241.893563
1          1  68.781904  162.310473
2          1  74.110105  212.740856
3          1  71.730978  220.042470
4          1  69.881796  206.349801
...      ...        ...         ...
6995       0  64.193082  137.840194
6996       0  65.799561  157.293743
6997       0  63.787050  120.838528
6998       0  61.186259  109.582356
6999       0  59.353831  106.108275

[7000 rows x 3 columns]

# x and y dividation

In [9]:
x = df[['Gender','Height']]
y = df [['Weight']]

In [10]:
x.head()

Gender     Height
0       1  73.847017
1       1  68.781904
2       1  74.110105
3       1  71.730978
4       1  69.881796

In [11]:
y.head()

Weight
0  241.893563
1  162.310473
2  212.740856
3  220.042470
4  206.349801

# divide the data into train test and split into 70% train and 30% test

In [12]:
xtrain , xtest, ytrain, ytest = train_test_split(x,y, test_size = .30, random_state = 30)
xtrain.head()

Gender     Height
5367       0  66.654636
491        1  68.445747
1062       1  70.978703
6521       0  63.641570
6233       0  69.598107

In [13]:
ytrain.head()

Weight
5367  156.764292
491   183.783383
1062  206.522974
6521  121.494688
6233  173.529945

In [14]:
xtest.head()

Gender     Height
2959       1  60.936236
740        1  70.869805
728        1  68.399719
5553       0  67.629133
6940       0  62.414768

In [15]:
ytest.head()

Weight
2959  152.349380
740   205.863934
728   171.329108
5553  163.112272
6940  137.053634

# linear Regression apply 

In [16]:
lreg = LinearRegression()
df = lreg.fit(xtrain,ytrain)

# Train and testing accuracy 

In [17]:
df.score(xtrain,ytrain)

0.8990186819901841

In [18]:
df.score(xtest,ytest)

0.9020642536665506

# Linear Regression with mathemetics calculation

In [19]:
#y = mx + c (m = coef_ and c = intercept_
m = lreg.coef_
m

array([[19.41926873,  5.9844502 ]])

In [20]:
c = lreg.intercept_
c

array([-245.56583327])

In [21]:
pred = (m * 69.881796) + c
print(pred)

[[1111.48754247  172.63829503]]


In [22]:
prediction = lreg.predict(xtest)
prediction

array([[138.52330563],
       [197.97025394],
       [183.18814847],
       ...,
       [122.89361962],
       [187.54864336],
       [ 82.82325662]])

In [23]:
x.head()

Gender     Height
0       1  73.847017
1       1  68.781904
2       1  74.110105
3       1  71.730978
4       1  69.881796

In [24]:
y.head()

Weight
0  241.893563
1  162.310473
2  212.740856
3  220.042470
4  206.349801

# mean_squared_error, mean_absolute_error measure

In [25]:
mse = mean_squared_error(ytest, lreg.predict(xtest))

In [26]:
mse

102.86603858158573

# knn regressor 


In [27]:
# from sklearn.neighbors import KNeighborsRegressor
knn = KNeighborsRegressor()

In [28]:
knn.fit(xtrain,ytrain) # train the model 

KNeighborsRegressor()

In [29]:
knn.score(xtrain,ytrain)

0.918996796690608

# test the model

In [30]:
knn.score(xtest,ytest)

0.8816905747936229

In [31]:
predic = knn.predict(xtest)
predic

array([[134.18698662],
       [209.0086161 ],
       [185.4556295 ],
       ...,
       [122.49267146],
       [187.64335848],
       [ 92.33329428]])

In [32]:
mse_knn = mean_squared_error(ytest, knn.predict(xtest))
mse_knn

124.26537146516661

# comparism between KNN and Linear Regression

In [33]:
print('the train score of liner_Regression is:--', df.score(xtrain,ytrain))
print('the train score of KNN is:--', knn.score(xtrain,ytrain))
print('the train score of liner_Regression is:--', df.score(xtest,ytest))
print('the train score of KNN is:--', knn.score(xtest,ytest))
print("the MSE for liner_Regression is ---::", mse)
print("the MSE for knn is ---::", mse_knn)



the train score of liner_Regression is:-- 0.8990186819901841
the train score of KNN is:-- 0.918996796690608
the train score of liner_Regression is:-- 0.9020642536665506
the train score of KNN is:-- 0.8816905747936229
the MSE for liner_Regression is ---:: 102.86603858158573
the MSE for knn is ---:: 124.26537146516661


# KNN classifier 

In [34]:
df1 = pd.read_csv('weight-height.csv')
df1.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

# Importing KKN classifier

In [35]:
# from sklearn.neighbors import KNeighborsClassifier
# knn_cla = KNeighborsClassifier(n_neighbors=10)

# sclaing the  Gender column

In [36]:
#randomSchelar is used
#from sklearn.preprocessing import LabelEncoder
# laben = LabelEncoder()
import warnings
warnings.filterwarnings('ignore')
df1['Gender'] = laben.fit_transform(df1[['Gender']])
df1.head(7000)


Gender     Height      Weight
0          1  73.847017  241.893563
1          1  68.781904  162.310473
2          1  74.110105  212.740856
3          1  71.730978  220.042470
4          1  69.881796  206.349801
...      ...        ...         ...
6995       0  64.193082  137.840194
6996       0  65.799561  157.293743
6997       0  63.787050  120.838528
6998       0  61.186259  109.582356
6999       0  59.353831  106.108275

[7000 rows x 3 columns]

# Data separation into x and y with train and test

In [37]:
x1 = df1[['Height', 'Weight']]
y1 = df1[['Gender']]

In [38]:
x1.head()

Height      Weight
0  73.847017  241.893563
1  68.781904  162.310473
2  74.110105  212.740856
3  71.730978  220.042470
4  69.881796  206.349801

In [39]:
y1.head()

Gender
0       1
1       1
2       1
3       1
4       1

In [40]:
x1.tail()

Height      Weight
8550  60.483946  110.565497
8551  63.423372  129.921671
8552  65.584057  155.942671
8553  67.429971  151.678405
8554  60.921791  131.253738

In [41]:
y1.tail()

Gender
8550       0
8551       0
8552       0
8553       0
8554       0

In [42]:
#from sklearn.model_selection import train_test_split
x1train, x1test,y1train, y1test=train_test_split(x1,y1, test_size = .30, random_state = 40)
x1train.head()

Height      Weight
6699  65.074119  149.230333
3507  67.089302  164.548646
7856  72.264748  188.437304
4000  68.662144  178.085845
6542  65.095308  156.062396

In [43]:
y1train.head()

Gender
6699       0
3507       1
7856       0
4000       1
6542       0

In [44]:
y1test.head()

Gender
369        1
3934       1
3438       1
6973       0
2190       1

In [45]:
x1test.head()

Height      Weight
369   69.915637  219.367917
3934  67.227445  182.546138
3438  67.391774  174.658931
6973  63.980472  137.033434
2190  69.514604  174.215001

# fit the model classifier Algorithmn apply

In [46]:
from sklearn.neighbors import KNeighborsClassifier
knn_cla = KNeighborsClassifier(n_neighbors=10)

In [47]:
df1 = knn_cla.fit(x1train,y1train)

# accuracy measure

In [48]:
df1.score(x1train, y1train)

0.9205076820307281

In [49]:
df1.score(x1test, y1test)

0.913517724970783

In [54]:
pre = knn_cla.predict(x1test)
pre

array([1, 1, 1, ..., 0, 1, 0])

# mean squared error 

In [50]:
from sklearn.metrics import mean_squared_error

In [55]:
KNN_classi_mse = mean_squared_error(y1test, knn_cla.predict(x1test))
KNN_classi_mse

0.08648227502921699